export const enum NAME_SCREENS {
  SPLASH_SCREEN = 'SplashScreen',
  LOGIN_SCREEN = 'LoginScreen',
  HOME_SCREEN = 'HomeScreen',
  BOTTOM_TAB = 'BottomTab',
  EVENT_NAVIGATOR = 'EventNavigator',
  MAP_NAVIGATOR = 'MapNavigator',
  PROFILE_NAVIGATOR = 'ProfileNavigator',
  ONBOARDING_SCREEN = 'OnBoardingScreen',
  SIGNUP_SCREEN = 'SignupScreen',
  VERIFICATION = 'VerificationScreen',
  RESETPASSWORD_SCREEN = 'ResetPasswordScreen',
  NEWPASSWORD_SCREEN = 'NewPassWord_Screen',
  EXPOLER_SCREEN = 'ExploreScreen',
  EVENTS_SCREEN = 'EventsScreen',
  ADDEVENT_SCREEN = 'AddEventScreen',
  MAP_SCREEN = 'MapScreen',
  PROFILE_SCREEN = 'ProfileScreen',
  MESSAGE_SCREEN = 'MessageScreen',
  CALENDER_SCREEN = 'CalenderScreen',
  BOOKMARK_SCREEN = 'BookMarkScreen',
  CONTACTUS_SCREEN = 'ContactUsSreen',
  SETTINGSCREEN = 'SettingsScreen',
  HELPSFAQS_SCREEN = 'HelpScreen',
  HOMEDRAWER_SCREEN = 'HomeDrawerScreen',
  DETAIL_SCREEN = 'DetailScreen',
}
